### ISSUE TITLE
Reimplementation

### ISSUE THREAD

**Issue by Diyorazh** [venkat-purdue/plug-and-play-priors#1]
Hi! I tried to run this code but I found the error:

May I ask why there is no BM3D?

Undefined function or variable 'BM3D'.

Error in ADMM_Core (line 75)
            [NA,imout] = BM3D(1,kparams.x/kparams.maxval,kparams.sigma);

Error in PlugAndPlayPriorScript (line 103)
[map_image,params]=ADMM_Core(InitialEst,sino,geom,Amatrix,params,kparams,mode);

Thank you!

**Comment by svvenkatakrishnan** [comment]
@Diyorazh : You will have to download the BM3D from http://www.cs.tut.fi/~foi/GCF-BM3D/index.html#ref_software and add it to the path in order to use it as a de-noiser in the PnP framework.

**Comment by Diyorazh** [comment]
![Screen Shot 2021-04-05 at 8 34 24 PM](https://user-images.githubusercontent.com/34129418/113574381-8fda5c80-964e-11eb-9525-e331a5b7d5f2.png)

Hi! I tried to do this but it seems that it's not successful. May I ask what's wrong with it?

![Screen Shot 2021-04-05 at 8 34 33 PM](https://user-images.githubusercontent.com/34129418/113574415-a7b1e080-964e-11eb-81d6-4df9b473fc02.png)

**Comment by Diyorazh** [comment]
Many thanks!:) @svvenkatakrishnan
